# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80607667a4e06f35fc05228f4fa9e54bfe857935f38fc716b0d63f3fe192919a8657caaa59e43b93fff989607b8b72e78d35831347275b12442fd7fd4d9d3816

test:
  secret_key_base: 8239fbf066e84aff85e63da32091e252b6778c56628a4e9c95ad381c7bdf7f38257277dfc107cd07cda90929fe67816f3842a79caf98dba7a0550ef8588981ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
